name: 16 - Working with environments
run-name: 16 - Working with environments | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging

jobs:
  echo-staging:
    runs-on: ubuntu-latest
    environment: staging

    env:
      MY_ENV_VALUE: ${{ vars.MY_ENV_VALUE || 'default value' }}

    steps:
      - name: Echo Vars
        run: |
          echo "Env Variable: $MY_ENV_VALUE"
  echo-prod:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}

    env:
      MY_ENV_VALUE: ${{ vars.MY_ENV_VALUE || 'default value' }}

    steps:
      - name: Echo Vars
        run: |
          echo "Env Variable: $MY_ENV_VALUE"